### ISSUE TITLE
Question regarding Eqn. 2 in paper

### ISSUE THREAD

**Issue by ff98li** [ethanbar11/ssm_2d#1]
Hi Ethan,

Congrats on your paper’s acceptance at ICLR and thank you for sharing the great work! I’m reaching out with a question about Eqn. 2 in the paper. I was going through the 2D-SSM derivation as well as its implementation, and I could be mistaken or overlooking something, so I would appreciate any clarification from the authors.

In Eqn 2, the formulation of 2D-SSM goes:
![Eqn2](https://github.com/ethanbar11/ssm_2d/assets/55061801/8f8c8dbd-8e3e-4841-a2ec-28a0c29ed346)

However, referring to Eqn 5 expanding the recurrent process later in the paper:
<img width="1329" alt="Screenshot 2024-05-07 at 10 29 14 AM" src="https://github.com/ethanbar11/ssm_2d/assets/55061801/97714a45-6265-459b-b9c5-a6b2e251ead6">

Maybe the right-most part of Eqn 2 could be written in the following form instead? (hadamard product in the right term)
<img width="500" alt="Screenshot 2024-05-07 at 10 29 14 AM" src="https://github.com/ethanbar11/ssm_2d/assets/55061801/757143fc-c82f-45f4-b874-12981b58299d">

Any insights would be very much appreciated!

Edit: Fixed a latex typo in the posted eqn.

**Comment by ethanbar11** [comment]
Hey Fei,
Firstly thanks for the interest in our paper.
I see now that there is a mistake in equation 5. it should be:
![image](https://github.com/ethanbar11/ssm_2d/assets/24264865/90cff4ba-c749-4bc9-a4ef-57831d3b85bc)
During the writing of the paper I consistently mixed up the names vertical and horizontal... Here it should be vertical (I hope!) and not horizontal.

Regarding your question:
Firstly, I assume you still have a typo, as I guess you meant $u_{i+1,j}$ in the lower last term.
Secondly, I agree, your equation is valid and is the actual one implemented. We will issue a new arxiv vesion soon.

Thanks a lot!
Ethan.

**Comment by ff98li** [comment]
Hi Ethan,
thanks a lot for answering! Indeed I missed the typo in the lower last term and it was intended to be $u_{i+1, j}$. Thank you for pointing it out!
On top of the new eqn. 5, I have another question: if $x^h_{0, 1}$ gets changed to $x^v_{0, 1}$, does this apply to eqn. 2 as well?

Thanks!

**Comment by ethanbar11** [comment]
Hi Fei,
can you expand on that? I'm not sure I completly understand your question.
i'll emphasize though that you were right regarding equation 2 - there is a mistake in that and we will replace it to what you suggested. 
also, we have a mistake in euqation 5 and will change from $x_{0,1}^h$ to $x_{0,1}^v$

Ethan.

**Comment by ff98li** [comment]
Hi Ethan,
sorry that I was a bit ambiguous back there. I was confused because I thought the original eqn. 5 was not wrong.. I failed to see the reason why $x^h_{0,1}$ needs to be changed to $x^v_{0,1}$. Any insights will be very much appreciated!

**Comment by ethanbar11** [comment]
Please update me for any other questions (we discussed further in the mail).
Otherwise, I'll set this as closed.
