### ISSUE TITLE
Question regarding the Figure 2 

### ISSUE THREAD

**Issue by anhtienng** [ethanbar11/ssm_2d#2]
Thank you for your wonderful work.

- Can you explain the 4 paths in Figure 2 ? 

- Moreover, there are some patches that the patches don't pass through, like (3,1) and (3,2), so the state (4,4) does not include the information of these patches. Is this correct ?

Thank you.

**Comment by ethanbar11** [comment]
- Yes. There are actually many more than four paths; this is just an illustration. The main idea is that, like any flow problem, there is an exponential number of paths from (1,1) to (n,n). The four paths shown are a subset of those.
- Yes, some paths won't contain all the data.
Thanks for the interest in our paper! Feel free to ask more questions.
