### ISSUE TITLE
Forward function of TwoDimensionalSSM

### ISSUE THREAD

**Issue by anhtienng** [ethanbar11/ssm_2d#3]
Thank you for your amazing work.

I am trying to understand the forward function of `TwoDimensionalSSM` in this [file](https://github.com/ethanbar11/ssm_2d/blob/main/models/mega/two_d_ssm_recursive.py).

But it is difficult for me to understand your idea behind this, especially after the 2-dimensional discrete Fourier transform.
Can you please explain the steps in this function ?

Thank you.

**Comment by ethanbar11** [comment]
I cleaned the code a little bit and added comments. Please let me know if it helped :).
If not, it would be better If you could refer me to the exact rows you don't understand.

**Comment by anhtienng** [comment]
I really appreciate your help.
- Could you please explain the meaning of the parameters `directions_amount`, `n_ssm`, `ndim` in [`main.py`?](https://github.com/ethanbar11/ssm_2d/blob/main/main.py) because the `help` sections of these parameters (I think) are not true. I think better explanation of these parameters could be easier for other people to understand the code.
- Can `directions_amount` be 1 ?
- You are calculating the output of 2D-SSM based on the global kernel (convolution model instead of recurrent mode), right ? (because the name of the file is `two_d_ssm_recursive.py` which makes me confused)
- What is the meaning of Fourier transform in `k_f_s = torch.fft.rfft2(k.float(), s=(2 * fft_len, 2 * fft_len))` (Line 318) ? 
- Is it possible to expand to non-square images ?
Thank you very much

**Comment by ethanbar11** [comment]
- fixed
- currently the code dooesn't support this option. Basically, directions_amount is the number of flips the kernel is going through and is used for causality.
- fixed
- basically, using the FFT in a way that is appropriate for the convolution. I suggest taking a look at the S4 paper code, they are doing the same (in 1-D) and explaining this.
- Yes, but not with the current code. You'd need to adjust the FFT and set zeros in the appropriate side of the kernel.
:)
